### ISSUE TITLE
Set up google forms for weekly submissions

### ISSUE THREAD

**Issue by harsh183** [harsh183/125-weekly-projects#14]
Should be the same form. Ask for Github link and some optional fields to check how people are doing. Ask people to list MVP features and some other nice to have features.

- [x] Week 1
- [x] Week 2
- [x] Week 3
- [x] Week 4
- [x] Week 5
- [x] Week 6
- [x] Week 7
- [x] Week 8

**Comment by harsh183** [comment]
Make sure to link the forum category as well.

**Comment by harsh183** [comment]
I think it should just be one form a week. We can include questions about the previous week too.

**Comment by harsh183** [comment]
Should be two a week.

**Comment by mpara17** [comment]
So to clarify, there is two submission forms: one that is for the "idea" and the other for the "project" submission. Idea is due Monday night and project due Wednesday?

**Comment by mpara0** [comment]
Update:

Idea Submission form: https://docs.google.com/forms/d/e/1FAIpQLSfnW8GRYw2BEK8kSVHHaB3QKIr0JRyDmiHjtU6g0nhRxs2h2Q/viewform

Project Submission form: https://docs.google.com/forms/d/e/1FAIpQLSc3rDLTncYE2j8pSS4-fZG7-SDpvuJ7DFe3vBl0KEouFT9f4g/viewform

**Comment by mpara17** [comment]
shared with you the forms

**Comment by harsh183** [comment]
Both look good. I'll make some edits to add some spicy questions as well.
