### ISSUE TITLE
Check if we have google analytics and if so remove it

### ISSUE THREAD

**Issue by harsh183** [harsh183/125-weekly-projects#19]
It's probably left behind from the template.

**Comment by mpara17** [comment]
why remove google analytics? wouldn't it be helpful for us to gauge a general interest on how many students visit certain parts of the site?

**Comment by harsh183** [comment]
Hmm... google is icky privacy wise. Maybe some open source analytics?

**Comment by harsh183** [comment]
New template has no analytics.
