### ISSUE TITLE
Add some ethics related articles here or there

### ISSUE THREAD

**Issue by harsh183** [harsh183/125-weekly-projects#34]
This isn't the space where the most ethics-y content is required but it can be good to have 1-3 ethics related links that people can check out (and even discuss I hope).

**Comment by mpara17** [comment]
we can recycle the CS125 CS Voices articles :')

**Comment by harsh183** [comment]
Not added anything for the last two but the rest are there. They're not too strong so I'll just leave it there but not like make a big deal or something.
