### ISSUE TITLE
Create a staff page at some point

### ISSUE THREAD

**Issue by harsh183** [harsh183/125-weekly-projects#7]

**Comment by harsh183** [comment]
Or maybe just keep this on the homepage. This can just be a simple list of names and link to profiles.

**Comment by harsh183** [comment]
The about page looks like a good place to start, I'm wondering if to include gravatars as well.

**Comment by mpara17** [comment]
Im thinking we can include names of the people who helped out for now. Having photos/gravatars are nice however

**Comment by harsh183** [comment]
Added both at /about. I think I got everyone but let me know if I missed someone by accident.
